"""Initial migration.

Revision ID: 8bcd7da6da0f
Revises: 
Create Date: 2020-07-19 15:01:46.346282

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8bcd7da6da0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient', sa.Column('id', sa.Integer(),
                                            nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('name'))
    op.create_table('recipe', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('instructions', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'ingredient_quantity',
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['ingredient_id'],
            ['ingredient.id'],
        ), sa.ForeignKeyConstraint(
            ['recipe_id'],
            ['recipe.id'],
        ), sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_quantity')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
