"""add recipe image url

Revision ID: 9419b6c81365
Revises: 8bcd7da6da0f
Create Date: 2020-07-31 19:34:07.314663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9419b6c81365'
down_revision = '8bcd7da6da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
